# Generated by Django 6.0.4 on 2026-04-14 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connectors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('batch_size', models.IntegerField(default=100)),
                ('offset', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('extracted', 'Extracted'), ('submitted', 'Submitted'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('raw_data', models.JSONField(default=dict)),
                ('edited_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectors.databaseconnection')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
